name: 自动更新数据和文章

on:
  schedule:
    # 上午8:30 (北京时间) - 获取韭研公社盘前数据
    - cron: '30 0 * * 1-5'   # UTC 00:30 = 北京时间 08:30
    # 下午15:30 (北京时间) - 获取涨停池和异动解析数据
    - cron: '30 7 * * 1-5'   # UTC 07:30 = 北京时间 15:30
    # 下午18:00 (北京时间) - 获取龙虎榜数据
    - cron: '00 10 * * 1-5'  # UTC 10:00 = 北京时间 18:00
    # 晚上19:00 (北京时间) - 获取通达信研报数据
    - cron: '00 11 * * 1-5'  # UTC 11:00 = 北京时间 19:00
    # 晚上20:00 (北京时间) - 获取融资融券数据 (新增)
    - cron: '00 12 * * 1-5'  # UTC 12:00 = 北京时间 20:00
    # 晚上23:30 (北京时间) - 获取韭研公社优秀阿呆文章
    - cron: '30 15 * * 1-5'  # UTC 15:30 = 北京时间 23:30
  workflow_dispatch:
    inputs:
      task_type:
        description: '选择执行的任务'
        required: true
        default: 'all'
        type: choice
        options:
        - 'all'
        - 'limitup'
        - 'jiuyan'
        - 'analysis'
        - 'dragon_tiger'
        - 'tdx_reports'
        - 'rzrq'  # 新增融资融券选项

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check-changes.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 检查文件结构
        run: |
          echo "当前目录内容:"
          ls -la
          echo "Python文件:"
          find . -name "*.py" -type f

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core

      - name: 安装 Python 依赖
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 python-docx pillow lxml

      - name: 确保目录存在
        run: |
          mkdir -p data articles analysis dragon_tiger tdx_value tdx_rztq assets .github/locks

      - name: 确定脚本文件名
        id: script-name
        run: |
          if [ -f "script.py" ]; then
            echo "script_file=script.py" >> $GITHUB_OUTPUT
          elif [ -f "scraper.py" ]; then
            echo "script_file=scraper.py" >> $GITHUB_OUTPUT
          elif [ -f "main.py" ]; then
            echo "script_file=main.py" >> $GITHUB_OUTPUT
          else
            echo "找不到Python脚本文件"
            exit 1
          fi

      - name: 确定执行任务
        id: determine-task
        run: |
          # 创建锁文件目录
          mkdir -p .github/locks
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # 手动触发：无限制执行
            echo "task=${{ github.event.inputs.task_type }}" >> $GITHUB_OUTPUT
            echo "manual_trigger=true" >> $GITHUB_OUTPUT
            echo "should_execute=true" >> $GITHUB_OUTPUT
            echo "手动触发任务: ${{ github.event.inputs.task_type }}"
          else
            # 自动触发：需要检查时间窗口和防重复
            echo "manual_trigger=false" >> $GITHUB_OUTPUT
            
            # 获取当前时间信息
            current_utc_hour=$(date -u +%H)
            current_utc_minute=$(date -u +%M)
            current_beijing_hour=$(TZ='Asia/Shanghai' date +%H)
            current_beijing_minute=$(TZ='Asia/Shanghai' date +%M)
            current_date=$(TZ='Asia/Shanghai' date +%Y%m%d)
            day_of_week=$(date -u +%u)  # 1-7 (Monday-Sunday)
            
            echo "当前UTC时间: $current_utc_hour:$current_utc_minute"
            echo "当前北京时间: $current_beijing_hour:$current_beijing_minute"
            echo "当前日期: $current_date, 星期: $day_of_week"
            
            # 初始化
            task_type=""
            should_execute="false"
            
            # 只在工作日执行
            if [ "$day_of_week" -ge "1" ] && [ "$day_of_week" -le "5" ]; then
              
              # 定义时间窗口匹配函数
              check_time_window() {
                local target_hour=$1
                local target_minute=$2
                local window_minutes=$3
                local current_total_minutes=$((current_utc_hour * 60 + current_utc_minute))
                local target_total_minutes=$((target_hour * 60 + target_minute))
                local diff=$((current_total_minutes - target_total_minutes))
                
                # 处理跨天情况
                if [ $diff -lt -720 ]; then
                  diff=$((diff + 1440))
                elif [ $diff -gt 720 ]; then
                  diff=$((diff - 1440))
                fi
                
                if [ $diff -ge -$window_minutes ] && [ $diff -le $window_minutes ]; then
                  return 0
                else
                  return 1
                fi
              }
              
              # 检查时间窗口（新增融资融券时间点）
              
              # 北京时间8:30 (UTC 00:30) - 韭研公社盘前数据
              if check_time_window 0 30 30; then
                task_type="jiuyan_morning"
                echo "匹配时间窗口: 韭研公社盘前数据 (北京时间8:30±30分钟)"              
              
              # 北京时间15:30 (UTC 07:30) - 涨停池和异动解析数据
              elif check_time_window 7 30 30; then
                task_type="afternoon_data"
                echo "匹配时间窗口: 涨停池和异动解析数据 (北京时间15:30±30分钟)"
              
              # 北京时间18:00 (UTC 10:00) - 龙虎榜数据
              elif check_time_window 10 0 30; then
                task_type="dragon_tiger"
                echo "匹配时间窗口: 龙虎榜数据 (北京时间18:00±30分钟)"
              
              # 北京时间19:00 (UTC 11:00) - 通达信研报数据
              elif check_time_window 11 0 30; then
                task_type="tdx_reports"
                echo "匹配时间窗口: 通达信研报数据 (北京时间19:00±30分钟)"
              
              # 北京时间20:00 (UTC 12:00) - 融资融券数据 (新增)
              elif check_time_window 12 0 30; then
                task_type="rzrq"
                echo "匹配时间窗口: 融资融券数据 (北京时间20:00±30分钟)"
              
              # 北京时间23:30 (UTC 15:30) - 韭研公社优秀阿呆
              elif check_time_window 15 30 30; then
                task_type="jiuyan_evening"
                echo "匹配时间窗口: 韭研公社优秀阿呆 (北京时间23:30±30分钟)"
              
              else
                task_type="unknown"
                echo "当前时间不在任何预定义的时间窗口内"
              fi
              
              # 检查是否已经执行过（防重复机制）
              if [ "$task_type" != "unknown" ] && [ "$task_type" != "" ]; then
                lock_file=".github/locks/${task_type}_${current_date}.lock"
                
                if [ -f "$lock_file" ]; then
                  echo "任务 $task_type 在 $current_date 已经执行过，跳过执行"
                  should_execute="false"
                else
                  echo "任务 $task_type 在 $current_date 首次执行，创建锁文件"
                  echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')" > "$lock_file"
                  should_execute="true"
                fi
              else
                should_execute="false"
              fi
              
            else
              task_type="weekend"
              should_execute="false"
              echo "周末时间，跳过执行"
            fi
            
            echo "task=$task_type" >> $GITHUB_OUTPUT
            echo "should_execute=$should_execute" >> $GITHUB_OUTPUT
          fi

      # 清理过期的锁文件（保留最近7天）
      - name: 清理过期锁文件
        if: steps.determine-task.outputs.manual_trigger == 'false'
        run: |
          if [ -d ".github/locks" ]; then
            find .github/locks -name "*.lock" -type f -mtime +7 -delete
            echo "已清理7天前的锁文件"
          fi

      # 简化后的自动触发任务执行
      - name: 执行韭研公社盘前数据
        if: steps.determine-task.outputs.task == 'jiuyan_morning' && steps.determine-task.outputs.should_execute == 'true'
        run: |
          echo "执行韭研公社盘前数据爬取..."
          python ${{ steps.script-name.outputs.script_file }} jiuyan 盘前纪要
          python ${{ steps.script-name.outputs.script_file }} jiuyan 盘前解读

      - name: 执行下午数据获取
        if: steps.determine-task.outputs.task == 'afternoon_data' && steps.determine-task.outputs.should_execute == 'true'
        run: |
          echo "执行下午数据获取..."
          python ${{ steps.script-name.outputs.script_file }} limitup
          python ${{ steps.script-name.outputs.script_file }} analysis

      - name: 执行龙虎榜数据获取
        if: steps.determine-task.outputs.task == 'dragon_tiger' && steps.determine-task.outputs.should_execute == 'true'
        run: |
          echo "执行龙虎榜数据获取..."
          python ${{ steps.script-name.outputs.script_file }} dragon_tiger

      - name: 执行通达信研报数据获取
        if: steps.determine-task.outputs.task == 'tdx_reports' && steps.determine-task.outputs.should_execute == 'true'
        run: |
          echo "执行通达信研报数据获取..."
          python ${{ steps.script-name.outputs.script_file }} tdx_reports

      # 新增：执行融资融券数据获取
      - name: 执行融资融券数据获取
        if: steps.determine-task.outputs.task == 'rzrq' && steps.determine-task.outputs.should_execute == 'true'
        run: |
          echo "执行融资融券数据获取..."
          python ${{ steps.script-name.outputs.script_file }} rzrq

      - name: 执行韭研公社优秀阿呆文章爬取
        if: steps.determine-task.outputs.task == 'jiuyan_evening' && steps.determine-task.outputs.should_execute == 'true'
        run: |
          echo "执行韭研公社优秀阿呆文章爬取..."
          python ${{ steps.script-name.outputs.script_file }} jiuyan 优秀阿呆

      # 手动触发的任务执行
      - name: 执行所有任务
        if: steps.determine-task.outputs.task == 'all' && steps.determine-task.outputs.manual_trigger == 'true'
        run: |
          echo "手动执行所有任务..."
          python ${{ steps.script-name.outputs.script_file }} all

      - name: 手动执行韭研公社任务
        if: steps.determine-task.outputs.task == 'jiuyan' && steps.determine-task.outputs.manual_trigger == 'true'
        run: |
          echo "手动执行韭研公社任务..."
          python ${{ steps.script-name.outputs.script_file }} jiuyan

      - name: 手动执行异动解析任务
        if: steps.determine-task.outputs.task == 'analysis' && steps.determine-task.outputs.manual_trigger == 'true'
        run: |
          echo "手动执行异动解析任务..."
          python ${{ steps.script-name.outputs.script_file }} analysis

      - name: 手动执行涨停池任务
        if: steps.determine-task.outputs.task == 'limitup' && steps.determine-task.outputs.manual_trigger == 'true'
        run: |
          echo "手动执行涨停池任务..."
          python ${{ steps.script-name.outputs.script_file }} limitup

      - name: 手动执行龙虎榜任务
        if: steps.determine-task.outputs.task == 'dragon_tiger' && steps.determine-task.outputs.manual_trigger == 'true'
        run: |
          echo "手动执行龙虎榜任务..."
          python ${{ steps.script-name.outputs.script_file }} dragon_tiger

      - name: 手动执行通达信研报任务
        if: steps.determine-task.outputs.task == 'tdx_reports' && steps.determine-task.outputs.manual_trigger == 'true'
        run: |
          echo "手动执行通达信研报任务..."
          python ${{ steps.script-name.outputs.script_file }} tdx_reports

      # 新增：手动执行融资融券任务
      - name: 手动执行融资融券任务
        if: steps.determine-task.outputs.task == 'rzrq' && steps.determine-task.outputs.manual_trigger == 'true'
        run: |
          echo "手动执行融资融券任务..."
          python ${{ steps.script-name.outputs.script_file }} rzrq

      - name: 检查文件变化
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "发现文件变化:"
            git status --porcelain
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "没有文件变化"
          fi

      - name: 配置 Git
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 提交更改
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          # 添加所有相关文件（包含融资融券目录）
          git add data/ articles/ analysis/ dragon_tiger/ tdx_value/ tdx_rztq/ assets/ .github/locks/ *.html
          
          # 生成提交信息
          task_name="${{ steps.determine-task.outputs.task }}"
          is_manual="${{ steps.determine-task.outputs.manual_trigger }}"
          
          if [ "$is_manual" = "true" ]; then
            # 手动触发的提交信息
            case $task_name in
              "all")
                commit_msg="手动更新: 所有数据和文章"
                ;;
              "jiuyan")
                commit_msg="手动更新: 韭研公社文章"
                ;;
              "analysis")
                commit_msg="手动更新: 异动解析数据"
                ;;
              "limitup")
                commit_msg="手动更新: 财联社涨停池数据"
                ;;
              "dragon_tiger")
                commit_msg="手动更新: 龙虎榜数据"
                ;;
              "tdx_reports")
                commit_msg="手动更新: 通达信研报数据"
                ;;
              "rzrq")  # 新增
                commit_msg="手动更新: 融资融券数据"
                ;;
              *)
                commit_msg="手动更新: $task_name"
                ;;
            esac
          else
            # 自动触发的提交信息
            case $task_name in
              "jiuyan_morning")
                commit_msg="自动更新: 韭研公社盘前数据 (北京时间8:30)"
                ;;
              "afternoon_data")
                commit_msg="自动更新: 涨停池和异动解析数据 (北京时间15:30)"
                ;;
              "dragon_tiger")
                commit_msg="自动更新: 龙虎榜数据 (北京时间18:00)"
                ;;
              "tdx_reports")
                commit_msg="自动更新: 通达信研报数据 (北京时间19:00)"
                ;;
              "rzrq")  # 新增
                commit_msg="自动更新: 融资融券数据 (北京时间20:00)"
                ;;
              "jiuyan_evening")
                commit_msg="自动更新: 韭研公社优秀阿呆文章 (北京时间23:30)"
                ;;
              "unknown")
                commit_msg="未识别时间点的更新"
                ;;
              "weekend")
                commit_msg="周末时间的更新"
                ;;
              *)
                commit_msg="自动更新数据: $task_name"
                ;;
            esac
          fi
          
          git commit -m "$commit_msg ($(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S'))" || echo "No changes to commit"
          git push

      - name: 输出执行结果
        run: |
          echo "=== 执行结果摘要 ==="
          echo "脚本文件: ${{ steps.script-name.outputs.script_file }}"
          echo "任务类型: ${{ steps.determine-task.outputs.task }}"
          echo "触发方式: ${{ github.event_name }}"
          echo "是否手动触发: ${{ steps.determine-task.outputs.manual_trigger }}"
          echo "是否应该执行: ${{ steps.determine-task.outputs.should_execute }}"
          echo "是否有变化: ${{ steps.check-changes.outputs.has_changes }}"
          echo "北京时间: $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          echo "UTC时间: $(date '+%Y-%m-%d %H:%M:%S')"
          
          # 显示锁文件状态
          if [ "${{ steps.determine-task.outputs.manual_trigger }}" = "false" ]; then
            echo "=== 锁文件状态 ==="
            if [ -d ".github/locks" ]; then
              echo "当前锁文件:"
              ls -la .github/locks/ || echo "锁文件目录为空"
            else
              echo "锁文件目录不存在"
            fi
          fi
          echo "==================="
