name: 自动更新涨停池数据

on:
  schedule:
    - cron: '00 7 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-spider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 运行爬虫脚本
        run: python scraper.py

      - name: 配置 Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 提交更改
        run: |
          git add data/ index.html json_viewer.html
          git commit -m "自动更新涨停池数据: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
