name: Scrape Limit-up Stocks

on:
  schedule:
    - cron: '52 13 * * 1-5'  # 工作日 UTC 11:37 (北京时间 19:37)
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]  # 保持仓库活跃

env:
  TZ: Asia/Shanghai

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # 如果需要部署到 GitHub Pages
      id-token: write   # 如果需要部署到 GitHub Pages
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 更新到最新版本
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4  # 更新到最新版本
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3 chardet beautifulsoup4 lxml
    
    - name: Create log directory
      run: mkdir -p logs
    
    - name: Run scraper with error handling
      run: |
        python scraper.py 2>&1 | tee logs/scraper_$(date +'%Y%m%d_%H%M%S').log
      continue-on-error: false
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git status --porcelain
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
    
    - name: Keep repo active
      run: |
        echo "Last run: $(date)" > .github/last_run.txt
        git add .github/last_run.txt
    
    - name: Configure Git
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local core.autocrlf false
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git add -A
        if git diff --staged --quiet; then
          echo "No staged changes to commit"
        else
          git commit -m "Update limit-up stocks data: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi
    
    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: scraper-logs
        path: logs/
        retention-days: 7
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "::error::Scraper workflow failed at $(date)"
        echo "Check the logs for more details"
