name: Scrape Limit-up Stocks

on:
  schedule:
    - cron: '45 11 * * *'  # 北京时间 19:37，对应 UTC 时间 11:37
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取完整历史以便推送
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3 chardet
    
    - name: Run scraper
      run: |
        python scraper.py
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push if changed
      run: |
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update limit-up stocks data: $(date +'%Y-%m-%d')" && git push)
